### ISSUE TITLE
Проблемы с sign in страницей

### ISSUE THREAD

**Issue by last1unicorn** [JustAwesomeGuy/shoronitor#4]
@JustAwesomeGuy спасай!,Нужно поставить в BODY шрифт не "нормал" , а жестко фиксированный - 16px

**Comment by JustAwesomeGuy** [comment]
Возможно все же не лучший вариант. Люди все же не зря шрифт меняют (ну у кого-то убогий экран на ноуте например). Сейчас ширина баттона (и возможно инпутов) считается от размера шрифта + падинги. Думаю если задать им высоту в пикселях будет лучшим решением

**Comment by JustAwesomeGuy** [comment]
баг устранил, все же через задание шрифта в боди. При другом способе в дальнейшем появляются различные проблемы
